import type {Metadata} from 'next';
import {cookies} from 'next/headers';
import {redirect} from 'next/navigation';
import Link from 'next/link';
import {ADMIN_COOKIE,validSession} from '@/lib/analytics/auth';
import {dashboard,eventLog,parseFilters} from '@/lib/analytics/dashboard';
import {countryName} from '@/lib/analytics/dimensions';
import {MetricTable,Distribution,Stat,DailyChart,n} from './report-components';
import {SearchPanel} from './search-panel';
import './analytics.css';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Traffic analytics | Fintiex admin',robots:{index:false,follow:false}};
const tabs=[['overview','Overview'],['acquisition','Acquisition'],['geo','Geography'],['devices','Devices'],['search','Search keywords'],['offers','Offer clicks'],['activity','Click & visit log']] as const;
export default async function Admin({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) {
 if(!await validSession((await cookies()).get(ADMIN_COOKIE)?.value))redirect('/admin/login');
 const params=await searchParams,f=parseFilters(params);
 const tab=tabs.some(([id])=>id===params.tab)?params.tab!:'overview';
 const page=Math.min(2000,Math.max(1,Math.floor(Number(params.page)||1)));
 const kind=['pageview','outbound'].includes(params.kind||'')?params.kind!:'';
 const link=(changes:Record<string,string>)=>'/admin?'+new URLSearchParams({...f,days:String(f.days),tab,...changes} as Record<string,string>);
 let data:Awaited<ReturnType<typeof dashboard>>|undefined,log:Awaited<ReturnType<typeof eventLog>>|undefined;
 try {[data,log]=await Promise.all([dashboard(f),tab==='activity'?eventLog(f,page,kind):Promise.resolve(undefined)]);}catch{}
 const filtered=Boolean(f.source||f.country||f.device||f.channel);
 return <div className="analytics analytics-full"><header className="analytics-heading"><div><p className="analytics-eyebrow">FINTIEX / ANALYTICS</p><h1>Your audience, in focus.</h1><p>Know what brings readers in—and which pages move them forward.</p></div><div className="analytics-account"><span className="analytics-status">{process.env.ANALYTICS_ENABLED==='true'?'Tracking enabled':'Tracking paused'}</span><form action="/api/admin/logout" method="post"><button className="analytics-signout">Sign out</button></form></div></header>
 <nav className="analytics-tabs" aria-label="Dashboard sections">{tabs.map(([id,label])=><Link key={id} href={link({tab:id})} aria-current={tab===id?'page':undefined}>{label}</Link>)}</nav>
 <div className="analytics-toolbar"><nav className="analytics-period" aria-label="Reporting period">{[1,7,30,90].map(d=><Link key={d} aria-current={d===f.days?'page':undefined} href={link({days:String(d)})}>{d===1?'Today':`${d} days`}</Link>)}</nav><span className="analytics-muted small">UTC · Includes today</span><Link className="analytics-refresh" href={link({refresh:String(Date.now())})}>↻ Refresh</Link></div>
 <form className="analytics-global-filters" action="/admin"><input type="hidden" name="days" value={f.days}/><input type="hidden" name="tab" value={tab}/><label>Source<select name="source" defaultValue={f.source}><option value="">All sources</option>{[...new Set<string>([...(data?.options.sources||[]),...(f.source?[f.source]:[])])].map(v=><option key={v}>{v}</option>)}</select></label><label>Channel<select name="channel" defaultValue={f.channel}><option value="">All channels</option>{[...new Set<string>([...(data?.options.channels||[]),...(f.channel?[f.channel]:[])])].map(v=><option key={v}>{v}</option>)}</select></label><label>Country<select name="country" defaultValue={f.country}><option value="">All countries</option>{[...new Set<string>([...(data?.options.countries||[]),...(f.country?[f.country]:[])])].map(v=><option key={v} value={v}>{countryName(v)}</option>)}</select></label><label>Device<select name="device" defaultValue={f.device}><option value="">All devices</option>{['Desktop','Mobile','Tablet','Unknown'].map(v=><option key={v}>{v}</option>)}</select></label><button>Apply filters</button>{filtered&&<Link href={`/admin?tab=${tab}&days=${f.days}`}>Clear filters</Link>}</form>
 {!data?<section className="analytics-panel"><h2>Reports are temporarily unavailable</h2><p>Please refresh in a moment. No totals are being estimated while storage is unavailable.</p></section>:<>
 <div className="analytics-stats full-stats"><Stat label="Page views" value={data.summary.views} previous={data.previous.views}/><Stat label="Daily visitors*" value={data.summary.visitors} previous={data.previous.visitors}/><Stat label="Outbound clicks" value={data.summary.clicks} previous={data.previous.clicks}/><Stat label="Active in last 5 minutes*" value={data.realtime} sub="Estimated visitors · selected audience"/></div>
 {tab==='overview'&&<><DailyChart days={f.days} rows={data.daily}/><div className="analytics-grid"><Distribution title="Where traffic comes from" rows={data.channels}/><Distribution title="Devices at a glance" rows={data.devices}/></div><MetricTable title="Top pages" rows={data.pages} note="Compare page views with clicks to external providers. Clicks measure interest, not completed applications."/><div className="analytics-grid"><MetricTable title="Top traffic sources" rows={data.sources}/><MetricTable title="Countries" rows={data.countries} labels={countryName}/></div></>}
 {tab==='acquisition'&&<><div className="analytics-grid"><Distribution title="Acquisition channels" rows={data.channels}/><Distribution title="Search engines" rows={data.engines}/></div><div className="analytics-grid"><MetricTable title="Traffic sources" rows={data.sources}/><MetricTable title="Referring websites" rows={data.referrers}/></div><MetricTable title="Campaign performance" rows={data.campaigns} note="Source / medium / campaign, from UTM tags."/><MetricTable title="Outbound destinations" rows={data.outbound} onlyClicks/></>}
 {tab==='offers'&&<><section className="analytics-notice"><strong>Which pages send readers to providers?</strong><p>Only explicitly labeled provider buttons count as offer clicks. These are expressions of interest, not completed applications or revenue. Historical outbound clicks remain in Acquisition; offer labels begin with this update.</p></section><MetricTable title="Offers and button placement" rows={data.offers} onlyClicks/><section className="analytics-panel"><h2>Pages generating offer clicks</h2><p className="analytics-muted small">Clicks per 100 page views can exceed 100 when a reader clicks several offers. Daily clickers are summed across days.</p>{data.offerPages.length?<div className="analytics-scroll"><table><thead><tr><th>Page</th><th>Views</th><th>Offer clicks</th><th>Daily clickers</th><th>Clicks / 100 views</th></tr></thead><tbody>{data.offerPages.map(r=><tr key={r.label}><td>{r.label}</td><td>{n(r.views)}</td><td>{n(r.clicks)}</td><td>{n(r.visitors)}</td><td>{r.views?(100*r.clicks/r.views).toFixed(1):'—'}</td></tr>)}</tbody></table></div>:<p className="analytics-empty">No labeled offer clicks recorded yet.</p>}</section></>}
 {tab==='geo'&&<><section className="analytics-notice"><strong>Approximate geography</strong><p>IP-based location can reflect a VPN, mobile carrier, or corporate network. It is not GPS location. Country is available for {n(data.coverage.geo)} of {n(data.summary.views)} page views in this selection. Older events remain Unknown because raw IP addresses were never retained.</p></section><div className="analytics-grid"><Distribution title="Audience by country" rows={data.countries} labels={countryName}/><MetricTable title="Countries" rows={data.countries} labels={countryName}/></div><div className="analytics-grid"><MetricTable title="Regions / states" rows={data.regions}/><MetricTable title="Cities" rows={data.cities}/></div><p className="analytics-muted small">This product includes GeoLite2 data created by <a className="analytics-back" href="https://www.maxmind.com" target="_blank" rel="noreferrer">MaxMind</a>. Lookup runs locally on our server; no raw IP is sent to a geolocation API. Database refreshes with package updates.</p></>}
 {tab==='devices'&&<><div className="analytics-grid"><Distribution title="Desktop, mobile & tablet" rows={data.devices}/><Distribution title="Browsers" rows={data.browsers}/></div><div className="analytics-grid"><MetricTable title="Devices" rows={data.devices}/><MetricTable title="Operating systems" rows={data.systems}/></div><div className="analytics-grid"><MetricTable title="Browser performance" rows={data.browsers}/><MetricTable title="Browser language" rows={data.languages}/></div><p className="analytics-muted small">Device classifications are inferred from browser information. {n(data.coverage.devices)} of {n(data.summary.views)} page views have a recognized device. Older events remain Unknown.</p></>}
 {tab==='search'&&<><div className="analytics-grid"><MetricTable title="Search engine visits" rows={data.engines} note="Traffic recorded on Fintiex, using the audience filters above."/><MetricTable title="Keywords supplied with visits" rows={data.keywords} note="Campaign terms (utm_term) and search terms explicitly supplied by a recognized referrer. These are not a complete organic keyword list."/></div><section className="analytics-notice">{n(data.coverage.hidden_keywords)} search page views have no keyword supplied. They remain “Not provided” in the activity log.</section><SearchPanel days={f.days} query={(params.q||'').slice(0,120)} importStatus={params.import}/></>}
 {tab==='activity'&&<section className="analytics-panel" id="activity"><div className="panel-title"><div><h2>Click & visit log</h2><p className="analytics-muted small">Source, geography, device, and available keyword for each recorded event.</p></div><a className="analytics-export" href={'/api/admin/export?'+new URLSearchParams({...f,days:String(f.days),kind,page:String(page)} as Record<string,string>)}>Export this page ↓</a></div><form className="analytics-filters" action="/admin#activity"><input type="hidden" name="tab" value="activity"/>{Object.entries(f).map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>)}<label>Activity<select name="kind" defaultValue={kind}><option value="">All activity</option><option value="pageview">Page views</option><option value="outbound">Outbound clicks</option></select></label><button>Filter log</button></form>{!log?.events.length?<p className="analytics-empty">No matching activity in this period.</p>:<div className="analytics-scroll"><table className="analytics-activity"><thead><tr>{['Time (UTC)','Activity','Page → destination','Source / channel','Location','Device / browser','Keyword','Campaign'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{log.events.map(e=><tr key={e.event_id}><td>{new Date(e.created_at).toISOString().slice(0,19).replace('T',' ')}</td><td><span className={`analytics-event ${e.kind}`}>{e.kind==='outbound'?'Outbound click':'Page view'}</span></td><td>{e.path}{e.target&&<small>→ {e.target}</small>}{e.offer&&<small>Offer: {e.offer} · {e.placement || 'Unspecified'}</small>}</td><td><strong>{e.source}</strong><small>{e.channel}{e.medium?' / '+e.medium:''}</small>{e.referrer&&<small>Ref: {e.referrer}</small>}</td><td>{countryName(e.country)}<small>{[e.city,e.region].filter(Boolean).join(', ')}</small></td><td>{e.device}<small>{e.browser} / {e.os}</small></td><td>{e.keyword || (e.search_engine?'Not provided':'—')}{e.keyword_type&&<small>{e.keyword_type}</small>}</td><td>{e.campaign || '—'}</td></tr>)}</tbody></table></div>}<nav className="analytics-pagination" aria-label="Activity pages"><span>{n(log?.total || 0)} matching events · Page {page}</span>{page>1&&<Link href={link({page:String(page-1),kind})}>← Newer</Link>}{page*50<(log?.total||0)&&page<2000&&<Link href={link({page:String(page+1),kind})}>Older →</Link>}</nav></section>}
 </>}
 <footer className="analytics-notes"><p>* Daily visitors are estimates, summed across days—not unique people across the entire period. Shared networks can undercount; network changes can overcount. Prior-period comparisons include today’s partial day. Known bots, admin pages, DNT and GPC are excluded; undetected bots can remain.</p><p>Tracking begins at installation. Geo, device, and keyword fields begin with this dashboard upgrade. Direct / unknown includes referrals browsers hide. No raw IP addresses, full referrer URLs, or calculator inputs are stored. Analytics records older than 90 days are removed automatically.</p></footer></div>;
}
