import {getSearchReport,searchConfigured} from '@/lib/analytics/search-reports';
import {n} from './report-components';
export async function SearchPanel({days,query,importStatus}:{days:number;query:string;importStatus?:string}) {
 const reports=await Promise.all(['google','bing'].map(engine=>getSearchReport(engine,days)));
 return <><section className="analytics-notice"><strong>Search queries are aggregate reports.</strong><p>Google and Bing usually hide the keyword on individual visits. Search Console and Webmaster Tools can report queries, clicks, impressions, CTR, and position in aggregate. These reports are not linked to individual visitors. Traffic filters above do not apply here; each report shows its own date range.</p></section>
 <form className="analytics-filters" action="/admin"><input type="hidden" name="tab" value="search"/><input type="hidden" name="days" value={days}/><label>Find a keyword<input name="q" defaultValue={query} placeholder="Search reported keywords" maxLength={120}/></label><button type="submit">Search keywords</button></form>
 <div className="analytics-grid">{['google','bing'].map((engine,index)=>{const report=reports[index];const name=engine==='google'?'Google':'Bing';const rows=report?.payload.rows.filter(r=>r.query.toLowerCase().includes(query.toLowerCase())).slice(0,100)||[];
 return <section className="analytics-panel" key={engine}><div className="panel-title"><h2>{name} search keywords</h2><span className="analytics-tag">{report?.origin==='csv'?'Imported snapshot':report?.status || (searchConfigured(engine)?'Connection unavailable':'Not connected')}</span></div>{report?<><p className="analytics-muted small">{report.start_date} – {report.end_date} · {report.origin==='api'?'Provider API':'CSV report'} · Updated {new Date(report.fetched_at).toISOString().slice(0,16).replace('T',' ')} UTC</p><div className="search-stats"><div><strong>{n(report.payload.totals.clicks)}</strong><span>Clicks</span></div><div><strong>{n(report.payload.totals.impressions)}</strong><span>Impressions</span></div><div><strong>{(report.payload.totals.ctr*100).toFixed(2)}%</strong><span>CTR</span></div><div><strong>{report.payload.totals.position.toFixed(1)}</strong><span>Avg. position</span></div></div><p className="analytics-muted small">Totals cover {report.payload.totalsScope} ({n(report.payload.rows.length)} query rows in this report). {report.origin==='csv'?'Snapshot dates are independent of the traffic date selector.':'Provider reports lag live traffic; the range ends three days ago.'} Up to 100 matching queries shown; anonymized queries may be omitted by the provider.</p>{rows.length?<div className="analytics-scroll"><table><thead><tr><th>Keyword</th><th>Clicks</th><th>Impressions</th><th>CTR</th><th>Position</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.query}</td><td>{n(r.clicks)}</td><td>{n(r.impressions)}</td><td>{(r.ctr*100).toFixed(2)}%</td><td>{r.position.toFixed(1)}</td></tr>)}</tbody></table></div>:<p className="analytics-empty">No matching queries in this report.</p>}</>:<><p className="analytics-empty">No {name} keyword report connected yet.</p><p className="analytics-muted">Import an exported query report below, or connect {name==='Google'?'read-only Google Search Console access for fintiex.com':'the fintiex.com Bing Webmaster API'} for automatic updates. A website visit alone cannot reveal a hidden search keyword.</p></>}<a className="analytics-back" target="_blank" rel="noreferrer" href={engine==='google'?'https://search.google.com/search-console/performance/search-analytics?resource_id=sc-domain%3Afintiex.com':'https://www.bing.com/webmasters/'}>Open {name==='Google'?'Search Console':'Bing Webmaster Tools'} ↗</a></section>;})}</div>
 <section className="analytics-panel"><h2>Import a keyword report</h2><p className="analytics-muted">Export the Queries table as CSV from Google Search Console or Bing Webmaster Tools. Select the exact report dates. Importing replaces that engine’s previous imported snapshot; it does not change your visitor records.</p>{importStatus&&<p role="status" className={importStatus==='success'?'analytics-notice':'analytics-error'}>{importStatus==='success'?'Keyword report imported.':'Import failed. Use a CSV with query, clicks, impressions, and position columns, valid dates, and a file under 2 MB.'}</p>}<form className="analytics-filters" action="/api/admin/search/import" method="post" encType="multipart/form-data"><label>Search engine<select name="engine"><option value="google">Google</option><option value="bing">Bing</option></select></label><label>Report starts<input name="start" type="date" required/></label><label>Report ends<input name="end" type="date" required max={new Date().toISOString().slice(0,10)}/></label><label>Query CSV<input type="file" name="file" accept=".csv,text/csv" required/></label><button type="submit">Import keyword report</button></form></section>
 </>;
}
