import { CardDecisionGuides } from "@/components/card-decision-guides";
import Link from "next/link";
import {cardsByCategory} from "@/lib/cards-server";
import {CardPickRow} from "@/components/card-pick-row";
import {BreadcrumbListSchema} from "@/components/schemas";
const guide={"category": "cashback", "title": "Cash-Back Credit Cards: Compare Fees & Reward Rules", "intro": "Compare flat-rate, category and rotating cash-back cards using current issuer terms.", "sections": [["Flat-rate or categories?", "Start with a simple uncapped rate as a baseline. A higher category rate only applies to eligible purchases and may stop at a spending cap."], ["Check activation and redemption", "Rotating categories may need activation. Compare redemption minimums, statement credits and any conditions such as earning a portion of cash back only when you pay."], ["Count the total cost", "Subtract annual fees and expected interest from rewards. A welcome offer is a one-time benefit, not a recurring earning rate."]], "links": [["/credit-cards/compare", "Compare card details"], ["/credit-cards/no-fee", "Explore annual fees"], ["/calculators/debt-payoff", "Model repayment"]]};
export const metadata={title:guide.title,description:guide.intro,alternates:{canonical:"/credit-cards/cash-back"}};
export default function Page(){const cards=cardsByCategory("cashback");return <>
<BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name:guide.title,href:'/credit-cards/cash-back'}]}/>
<header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-10"><span className="chip chip-lime mb-5">Credit card comparison</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight max-w-4xl">{guide.title}</h1><p className="text-lg text-mute mt-6 max-w-3xl">{guide.intro}</p><a href="#compare" className="pill pill-ink mt-6">Compare listed cards ↓</a></header>
<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">What to compare before applying</h2><div className="grid md:grid-cols-3 gap-5">{guide.sections.map(([title,text])=><article key={title} className="card p-6"><h3 className="font-bold text-xl mb-3">{title}</h3><p className="text-mute leading-relaxed">{text}</p></article>)}</div></section>
<section id="compare" className="max-w-(--max-w-page) mx-auto px-6 py-10"><h2 className="font-display text-3xl font-bold mb-4">Compare the cards in our directory</h2><p className="text-mute mb-8 max-w-3xl">This is a selection of products, not the entire market. Offers can vary by applicant and change over time. Verify current bonuses, rates, fees, and eligibility in the issuer’s application disclosures before applying. List order is not a guarantee of suitability or approval.</p><div className="space-y-5">{cards.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>
<section className="max-w-(--max-w-page) mx-auto px-6 py-12"><h2 className="font-display text-2xl font-bold mb-4">Continue your comparison</h2><div className="flex flex-wrap gap-4">{guide.links.map(([href,label])=><Link className="pill pill-ghost" key={href} href={href!}>{label}</Link>)}</div><p className="text-sm text-mute mt-8">Comparison guidance reviewed September 12, 2026. This date does not certify every issuer offer as current. Sources: <a className="underline" href="https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/">CFPB credit card terms</a> and each linked issuer’s application disclosures. <Link className="underline" href="/editorial-policy">Editorial policy</Link>.</p></section><CardDecisionGuides comparisonHref="/credit-cards/cash-back" /></>}
