import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {BreadcrumbListSchema,FinancialProductSchema} from '@/components/schemas';
import {CardArt} from '@/components/card-art';
import {CardPickRow} from '@/components/card-pick-row';
import {fullCardName,formatAnnualFee,formatAprRange,formatPct,formatFeePct} from '@/lib/cards';
import {loadCards,loadCard,relatedCards} from '@/lib/cards-server';
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return loadCards().map(c=>({slug:c.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const c=loadCard((await params).slug);if(!c)return {title:'Card not found'};return {title:`${fullCardName(c)}: Fees, Rewards & Offer Status`,description:`Compare ${fullCardName(c)} details, official sources and offer availability. See which fees and rewards have been confirmed before applying.`,alternates:{canonical:`/credit-cards/${c.slug}`}};}
export default async function Page({params}:Props){
 const card=loadCard((await params).slug);if(!card)notFound();
 const name=fullCardName(card),related=relatedCards(card,3);
 const fees=[['Annual fee',formatAnnualFee(card.annual_fee)],['Purchase APR',formatAprRange(card.apr_purchase)],['Introductory APR',card.intro_terms||'Check issuer'],['Balance transfer APR',formatAprRange(card.apr_balance_transfer)],['Cash advance APR',formatPct(card.apr_cash_advance)],['Balance transfer fee',formatFeePct(card.balance_transfer_fee)],['Foreign transaction fee',formatFeePct(card.foreign_tx_fee)]];
 const providerButton=(placement:string)=><a className="pill pill-ink" href={card.application_url} data-offer={card.slug} data-placement={placement} target="_blank" rel="nofollow noopener noreferrer">{card.availability==='retired'?'See issuer information':'Check current issuer terms'} ↗</a>;
 return <article className="bg-bg">
 <BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name,href:`/credit-cards/${card.slug}`}]}/>
 <FinancialProductSchema name={name} description={card.audit_note} slug={`/credit-cards/${card.slug}`} brandName={card.issuer} category="CreditCard" apr={card.apr_purchase?`${card.apr_purchase.min} to ${card.apr_purchase.max}`:undefined}/>
 <header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-12"><Link className="u-link text-sm" href="/credit-cards">Credit card directory</Link><div className="grid lg:grid-cols-[1fr_auto] items-center gap-10 mt-6"><div><span className="chip chip-lime mb-5">Card details &amp; source review</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight mb-5">{name}</h1><p className="text-lg text-mute leading-relaxed mb-5">Review the costs, rewards and application terms that matter for your comparison. Confirm the offer shown to you at the issuer before applying.</p><p className="text-sm text-mute mb-6">Published by Fintiex · Updated {card.last_updated} · <Link className="underline" href="/editorial-policy">How we check information</Link></p>{providerButton('card-review-hero')}</div><CardArt card={card} width={320}/></div></header>
 <section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><div className="card p-7 border-l-4 border-lime"><h2 className="font-display font-bold text-2xl mb-3">{card.availability==='retired'?'No longer a current application offer':card.source_checked?'Official source check':'Offer verification pending'}</h2><p className="text-mute leading-relaxed">{card.audit_note}</p><p className="text-sm mt-4">{card.source_checked?`Selected facts checked ${card.source_checked}. `:`Verification attempted ${card.audit_attempted}. `}<a className="underline" href={card.source_url||card.application_url} target="_blank" rel="noopener noreferrer">Official source ↗</a></p></div></section>
 {card.availability!=='retired'&&<>
 <section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">Rates and fees</h2><div className="card-flush overflow-hidden"><dl>{fees.map(([label,value])=><div key={label} className="grid md:grid-cols-2 gap-2 border-b border-line last:border-0 px-6 py-4"><dt className="text-mute">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl></div>{card.annual_fee_note&&<p className="text-sm mt-4">{card.annual_fee_note}</p>}<p className="text-sm text-mute mt-4">“Check issuer” means we have not confirmed that field. It does not mean the fee or interest is zero. Variable APRs can change, and your applicable rate depends on the issuer’s terms.</p></section>
 <section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><div className="grid md:grid-cols-2 gap-6"><div className="card p-7"><h2 className="font-display font-bold text-2xl mb-4">Rewards and welcome offer</h2><p className="mb-4">{card.signup_bonus||'No current welcome offer has been confirmed in this review. Check the issuer for personalized or public offers.'}</p><ul className="space-y-3 text-mute">{card.perks.map(p=><li key={p}>{p}</li>)}</ul>{!card.perks.length&&<p className="text-mute">Check earning categories, spending caps, redemption rules and exclusions at the issuer. We are withholding unconfirmed reward rates.</p>}</div><div className="card p-7"><h2 className="font-display font-bold text-2xl mb-4">Before you apply</h2><ul className="space-y-3 text-mute">{card.drawbacks.map(p=><li key={p}>{p}</li>)}<li>Compare the annual cost with benefits you expect to use. Subtract fees and interest from any reward estimate.</li><li>Confirm any bonus spending deadline and eligibility exclusions. Avoid extra spending solely to earn a promotion.</li><li>We do not publish a minimum approval score without an issuer source. Approval depends on the issuer’s assessment of your application.</li></ul></div></div></section>
 </>}
 <section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><div className="card p-7"><h2 className="font-display font-bold text-2xl mb-4">How to decide whether this card fits</h2><p className="text-mute leading-relaxed mb-5">Start with your purpose: everyday spending, travel, managing existing debt, business purchases or building credit history. Compare products serving that purpose, then check the official pricing disclosure. A high reward multiplier only helps on eligible purchases and at a redemption value you can actually use.</p><div className="flex flex-wrap gap-3">{providerButton('card-review-body')}<Link className="pill pill-ghost" href="/credit-cards/compare">Compare card details</Link></div><p className="text-sm text-mute mt-5">Application links do not establish a paid partnership. See our <Link href="/editorial-policy" className="underline">advertising disclosure</Link>. No individual financial advice or approval guarantee is provided.</p></div></section>
 {related.length>0&&<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display font-bold text-3xl mb-6">Compare similar cards</h2><div className="space-y-5">{related.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>}
 </article>;
}
