import assert from 'node:assert/strict';
import {randomUUID, createHash} from 'node:crypto';
import {Pool} from 'pg';
const url = process.env.ANALYTICS_DATABASE_URL;
if (!url || !new URL(url).pathname.endsWith('/fintiex_analytics_test')) throw new Error('Tests require the isolated fintiex_analytics_test database');
const pool = new Pool({connectionString:url});
const base = 'http://localhost:3047';
const ids = [];
const headers = {'content-type':'application/json',origin:base,'sec-fetch-site':'same-origin','x-real-ip':'192.0.2.10','user-agent':'Mozilla/5.0 TestBrowser'};
let auth = {}; let tokenHash;
async function login(password=process.env.ANALYTICS_ADMIN_PASSWORD, origin=base, ip='192.0.2.11') {
  return fetch(base+'/api/admin/login',{method:'POST',redirect:'manual',headers:{origin,'content-type':'application/x-www-form-urlencoded','x-real-ip':ip},body:new URLSearchParams({username:'admin',password})});
}
async function send(overrides={},custom={}) {
  const id = randomUUID(); ids.push(id);
  const body = {id,kind:'pageview',path:'/savings',referrer:'https://www.google.com/search?q=private',...overrides};
  return fetch(base+'/api/analytics',{method:'POST',headers:{...headers,...custom},body:JSON.stringify(body)});
}
try {
  const unauthorized = await fetch(base+'/admin',{redirect:'manual'}); assert.equal(unauthorized.status,303);
  assert.match(unauthorized.headers.get('location'),/admin\/login/);
  assert.equal(unauthorized.headers.get('www-authenticate'),null);
  assert.match(unauthorized.headers.get('cache-control'),/no-store/);
  assert.equal((await fetch(base+'/admin/private.csv',{redirect:'manual'})).status,303);
  const form = await fetch(base+'/admin/login'); assert.equal(form.status,200); assert.match(await form.text(),/current-password/);
  assert.equal((await login(undefined,'https://evil.example')).status,403);
  assert.match((await login('wrong')).headers.get('location'),/error=invalid/);
  const signedIn = await login(); assert.equal(signedIn.status,303);
  const cookie = signedIn.headers.get('set-cookie'); assert.match(cookie,/HttpOnly/i); assert.match(cookie,/SameSite=lax/i); assert.match(cookie,/Max-Age=28800/i);
  auth = {cookie:cookie.split(';')[0]};
  const token=auth.cookie.split('=')[1]; tokenHash=createHash('sha256').update(token).digest('hex');
  assert.equal((await fetch(base+'/admin',{headers:{cookie:'fintiex_admin_session='+ '0'.repeat(64)},redirect:'manual'})).status,303);
  const id=randomUUID();ids.push(id);
  assert.equal((await send({id})).status,204);
  assert.equal((await send({id})).status,204);
  assert.equal((await send({kind:'outbound',target:'https://bank.example/apply?email=private',offer:'test-card',placement:'card-comparison'})).status,204);
  assert.equal((await send({source:'newsletter',medium:'email',campaign:'weekly_rates'})).status,204);
  assert.equal((await send({}, {'user-agent':'Googlebot'})).status,204);
  assert.equal((await send({}, {'user-agent':'Chrome-Lighthouse',origin:'null','sec-fetch-site':'none'})).status,204,'audit bots are ignored without a console error');
  assert.equal((await send({}, {dnt:'1'})).status,204);
  assert.equal((await send({}, {'sec-gpc':'1'})).status,204);
  assert.equal((await send({}, {origin:'https://evil.example'})).status,403);
  assert.equal((await send({path:'/admin'})).status,400);
  assert.equal((await send({path:'/savings?email=private'})).status,400);
  assert.equal((await send({id:'-'.repeat(36)})).status,400);
  assert.equal((await send({campaign:'x'.repeat(3000)})).status,413);
  const {rows} = await pool.query('SELECT * FROM fintiex_analytics WHERE event_id = ANY($1::uuid[])',[ids]);
  assert.equal(rows.length,3,'duplicate, bot, DNT, GPC, malformed and cross-site requests excluded');
  assert.equal(rows.filter(r=>r.kind==='pageview').length,2);
  assert.equal(rows[0].source,'Google');
  assert.equal(new Set(rows.map(r=>r.visitor)).size,1,'one daily visitor');
  assert.equal(rows.find(r=>r.kind==='outbound').target,'bank.example');
  assert.equal(rows.find(r=>r.kind==='outbound').offer,'test-card');
  assert.equal(rows.find(r=>r.kind==='outbound').placement,'card-comparison');
  const offers = await fetch(base+'/admin?tab=offers&days=7',{headers:auth});
  assert.equal(offers.status,200);assert.match(await offers.text(),/test-card/);
  assert.ok(!JSON.stringify(rows).includes('private'),'sensitive query strings stripped');
  const admin = await fetch(base+'/admin?tab=activity&days=7',{headers:auth});
  assert.equal(admin.status,200);assert.match(admin.headers.get('cache-control'),/no-store/);
  const html=await admin.text();assert.match(html,/Google/);assert.match(html,/weekly_rates/);assert.match(html,/bank.example/);
  const geoId=randomUUID();ids.push(geoId);
  assert.equal((await send({id:geoId,source:'bing',ad:'bing',keyword:'high yield savings',keywordType:'campaign'}, {'x-real-ip':'8.8.8.8','accept-language':'en-US,en;q=0.9','user-agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'})).status,204);
  const geo=(await pool.query('SELECT country,device,browser,os,language,source,channel,keyword FROM fintiex_analytics WHERE event_id=$1',[geoId])).rows[0];
  assert.equal(geo.country,'US');assert.equal(geo.device,'Mobile');assert.equal(geo.source,'Bing');assert.equal(geo.channel,'Paid search');assert.equal(geo.keyword,'high yield savings');assert.equal(geo.language,'en-US');assert.equal(geo.browser,'Safari');
  const geoPage=await fetch(base+'/admin?tab=activity&country=US&device=Mobile&source=Bing',{headers:auth});const geoHtml=await geoPage.text();assert.match(geoHtml,/United States/);assert.match(geoHtml,/high yield savings/);assert.match(geoHtml,/Paid search/);
  const exportRes=await fetch(base+'/api/admin/export?country=US&device=Mobile&source=Bing',{headers:auth});assert.equal(exportRes.status,200);assert.match(await exportRes.text(),/high yield savings/);
  const keywordCsv=new FormData();keywordCsv.set('engine','bing');keywordCsv.set('start','2026-09-01');keywordCsv.set('end','2026-09-08');keywordCsv.set('file',new File(['Top queries,Clicks,Impressions,CTR,Position\n"savings, best rates",4,80,5%,12.5\n'], 'Queries.csv',{type:'text/csv'}));
  const imported=await fetch(base+'/api/admin/search/import',{method:'POST',headers:{...auth,origin:base},body:keywordCsv,redirect:'manual'});assert.equal(imported.status,303);assert.match(imported.headers.get('location'),/import=success/);
  const searchPage=await fetch(base+'/admin?tab=search',{headers:auth});const searchHtml=await searchPage.text();assert.match(searchHtml,/savings, best rates/);assert.match(searchHtml,/Imported snapshot/);
  const clickLog = await fetch(base+'/admin?tab=activity&days=7&kind=outbound&source=Google',{headers:auth});
  const logHtml = (await clickLog.text()).split('id="activity"')[1];
  assert.ok(logHtml); assert.match(logHtml,/bank.example/); assert.match(logHtml,/Google/); assert.match(logHtml,/1<!-- --> matching events/);
  const emptyLog = await fetch(base+'/admin?tab=activity&source=not_a_source',{headers:auth}); assert.match(await emptyLog.text(),/No matching activity/);
  assert.equal((await fetch(base+'/api/admin/logout',{method:'POST',headers:{...auth,origin:'https://evil.example'}})).status,403);
  await pool.query("UPDATE fintiex_admin_sessions SET expires_at=now()-interval '1 second' WHERE token_hash=$1",[tokenHash]);
  assert.equal((await fetch(base+'/admin',{headers:auth,redirect:'manual'})).status,303,'expired session rejected');
  await pool.query("UPDATE fintiex_admin_sessions SET expires_at=now()+interval '1 hour' WHERE token_hash=$1",[tokenHash]);
  const logout=await fetch(base+'/api/admin/logout',{method:'POST',redirect:'manual',headers:{...auth,origin:base}}); assert.equal(logout.status,303);
  assert.equal((await fetch(base+'/admin',{headers:auth,redirect:'manual'})).status,303,'logged-out session revoked');
  for(let i=0;i<10;i++) await login('wrong',base,'192.0.2.12');
  assert.match((await login('wrong',base,'192.0.2.12')).headers.get('location'),/error=limited/);
  console.log('PASS: form login, logout revocation, cookie protection, CSRF, throttling, click/source filters, authentication, no-store, ingestion, deduplication, daily visitor grouping, referral sanitization, campaigns, outbound clicks, bot/DNT/GPC filtering, origin checks, size/path validation and dashboard reporting');
} finally {
  await pool.query('DELETE FROM fintiex_analytics WHERE event_id = ANY($1::uuid[])',[ids]);
  if(tokenHash) await pool.query('DELETE FROM fintiex_admin_sessions WHERE token_hash=$1',[tokenHash]);
  await pool.query('DELETE FROM fintiex_admin_login_attempts');
  await pool.query("DELETE FROM fintiex_search_reports WHERE engine='bing' AND period_days=0");
  await pool.end();
}
