/** Provider-checked savings observations. No generated historical rates. */
export type SavingsOffer = {key:string;name:string;apy:number|null;minimum:number;condition:string;source:string;checked:string;review:string;closed?:boolean};
export const SAVINGS_CHECKED='2026-09-11';
export const savingsOffers: SavingsOffer[] = [
 {key:'bread',name:'Bread Savings High Yield Savings',apy:3.95,minimum:100,condition:'$100 opening deposit. Variable APY; no monthly maintenance fee.',source:'https://opensavings.breadfinancial.com/',checked:SAVINGS_CHECKED,review:'/reviews/bread'},
 {key:'bask',name:'Bask Interest Savings',apy:3.75,minimum:0,condition:'Base APY. Fund within 15 business days. Expired new-customer promotions are excluded.',source:'https://baskbank.com/current-rates',checked:SAVINGS_CHECKED,review:'/reviews/bask'},
 {key:'cit',name:'CIT Platinum Savings',apy:3.75,minimum:100,condition:'This APY requires $5,000 or more; lower balances earn 0.25%. This is not Savings Connect.',source:'https://www.cit.com/cit-bank/bank/savings',checked:SAVINGS_CHECKED,review:'/reviews/cit'},
 {key:'cit-savings-connect',name:'CIT Savings Connect',apy:3.65,minimum:100,condition:'$100 to open; no account opening or maintenance fees. Separate from Platinum Savings.',source:'https://www.cit.com/cit-bank/bank/savings',checked:SAVINGS_CHECKED,review:'/savings/accounts/cit-savings-connect'},
 {key:'marcus',name:'Marcus Online Savings Account',apy:3.40,minimum:0,condition:'Standard variable APY. No fees or minimum deposit; temporary referral boosts excluded.',source:'https://www.marcus.com/us/en/comparison',checked:SAVINGS_CHECKED,review:'/reviews/marcus'},
 {key:'sofi',name:'SoFi Checking and Savings',apy:3.10,minimum:0,condition:'Requires eligible direct deposit or qualifying deposits. Temporary promotional boosts excluded; lower rates apply without qualification.',source:'https://www.sofi.com/banking/',checked:SAVINGS_CHECKED,review:'/reviews/sofi'},
 {key:'ally',name:'Ally Bank Savings',apy:3.00,minimum:0,condition:'No minimum opening deposit or monthly maintenance fee. Certain withdrawals limited to 10 per statement cycle.',source:'https://www.ally.com/bank/view-rates/',checked:SAVINGS_CHECKED,review:'/reviews/ally'},
 {key:'lendingclub-savings',name:'Happen Bank LevelUp Savings (formerly LendingClub)',apy:4.00,minimum:0,condition:'4.00% requires $250 or more in deposits per evaluation period; otherwise 3.00%. Introductory evaluation rules apply. No minimum opening deposit.',source:'https://www.happen.com/',checked:SAVINGS_CHECKED,review:'/savings/accounts/lendingclub-high-yield-savings'},
 {key:'synchrony',name:'Synchrony High Yield Savings',apy:null,minimum:0,condition:'No minimum deposit or monthly fees. The current numeric APY could not be independently confirmed; check the provider.',source:'https://www.synchrony.com/banking/products/high-yield-savings',checked:SAVINGS_CHECKED,review:'/savings/accounts/synchrony-high-yield-savings'},
 {key:'amex-savings',name:'American Express High Yield Savings',apy:null,minimum:0,condition:'No opening or monthly maintenance fee and no minimum deposit. Confirm the current APY with American Express.',source:'https://www.americanexpress.com/en-us/banking/online-savings/high-yield-savings-account/',checked:SAVINGS_CHECKED,review:'/reviews/amex-savings'},
 {key:'capital-one',name:'Capital One 360 Performance Savings',apy:null,minimum:0,condition:'No minimum balance or monthly fee. Confirm the current numeric APY with Capital One.',source:'https://www.capitalone.com/bank/savings-accounts/online-performance-savings-account/',checked:SAVINGS_CHECKED,review:'/savings/accounts/capital-one-360-performance-savings'},
 {key:'discover-savings',name:'Discover Online Savings',apy:null,minimum:0,condition:'Not offered to new applicants. Existing customers should follow their account notices; new customers can compare Capital One or other accounts.',source:'https://www.discover.com/online-banking/',checked:SAVINGS_CHECKED,review:'/reviews/discover-savings',closed:true},
];
export function savingsOffer(key:string){const offer=savingsOffers.find(o=>o.key===key);if(!offer)throw new Error('Unknown savings offer');return offer;}
export function rateLabel(rate:number|null){return rate===null?'Check provider':rate.toFixed(2)+'%';}
export const hysaOptions=savingsOffers.filter(o=>o.apy!==null&&!o.closed).sort((a,b)=>b.apy!-a.apy!).map(o=>({lender:o.name,apy:o.apy!,detail:o.condition,href:o.review,tag:undefined as string|undefined}));
