import Link from "next/link";
import {cardsByCategory} from "@/lib/cards-server";
import {CardPickRow} from "@/components/card-pick-row";
import {BreadcrumbListSchema} from "@/components/schemas";
const guide={"category": "student", "title": "Student Credit Cards: Compare Costs & Eligibility", "intro": "Explore student-card listings and confirm eligibility, current terms and credit reporting directly with the issuer.", "sections": [["Student status does not ensure approval", "Check the issuer\u2019s student and income requirements. There is no universal student-card approval score."], ["Start with manageable costs", "Compare annual fees, deposits if applicable, and the cost of carrying a balance. A smaller credit limit can still require careful spending and repayment."], ["Build a payment routine", "Set reminders, review statements and budget for required payments. Check what happens to the account when you graduate."]], "links": [["/credit-cards/compare", "Compare card details"], ["/credit-cards/no-fee", "Explore annual fees"], ["/calculators/debt-payoff", "Model repayment"]]};
export const metadata={title:guide.title,description:guide.intro,alternates:{canonical:"/credit-cards/student"}};
export default function Page(){const cards=cardsByCategory("student");return <>
<BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name:guide.title,href:'/credit-cards/student'}]}/>
<header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-10"><span className="chip chip-lime mb-5">Credit card comparison</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight max-w-4xl">{guide.title}</h1><p className="text-lg text-mute mt-6 max-w-3xl">{guide.intro}</p><a href="#compare" className="pill pill-ink mt-6">Compare listed cards ↓</a></header>
<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">What to compare before applying</h2><div className="grid md:grid-cols-3 gap-5">{guide.sections.map(([title,text])=><article key={title} className="card p-6"><h3 className="font-bold text-xl mb-3">{title}</h3><p className="text-mute leading-relaxed">{text}</p></article>)}</div></section>
<section id="compare" className="max-w-(--max-w-page) mx-auto px-6 py-10"><h2 className="font-display text-3xl font-bold mb-4">Compare the cards in our directory</h2><p className="text-mute mb-8 max-w-3xl">This is a selection of products, not the entire market. Offers can vary by applicant and change over time. Verify current bonuses, rates, fees, and eligibility in the issuer’s application disclosures before applying. List order is not a guarantee of suitability or approval.</p><div className="space-y-5">{cards.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>
<section className="max-w-(--max-w-page) mx-auto px-6 py-12"><h2 className="font-display text-2xl font-bold mb-4">Continue your comparison</h2><div className="flex flex-wrap gap-4">{guide.links.map(([href,label])=><Link className="pill pill-ghost" key={href} href={href!}>{label}</Link>)}</div><p className="text-sm text-mute mt-8">Comparison guidance reviewed September 12, 2026. This date does not certify every issuer offer as current. Sources: <a className="underline" href="https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/">CFPB credit card terms</a> and each linked issuer’s application disclosures. <Link className="underline" href="/editorial-policy">Editorial policy</Link>.</p></section></>}
