import { CardDecisionGuides } from "@/components/card-decision-guides";
import Link from "next/link";
import {cardsByCategory} from "@/lib/cards-server";
import {CardPickRow} from "@/components/card-pick-row";
import {BreadcrumbListSchema} from "@/components/schemas";
const guide={"category": "secured", "title": "Secured Credit Cards: Compare Deposits, Fees & Terms", "intro": "Compare secured credit cards by security deposit, annual fee, credit reporting, and deposit-return rules. Approval, a higher credit score, and an upgrade are not guaranteed.", "sections": [["A deposit is different from a fee", "A secured card generally requires a security deposit. Check the required amount, how it relates to your credit limit, and when it can be returned. Budget for that deposit separately from any annual fee and from the monthly bill; the deposit does not replace payments."], ["Check credit reporting and upgrade rules", "Ask which credit bureaus receive account activity and whether the issuer reviews accounts for an unsecured upgrade. A review date is not a promised upgrade date. Confirm how account closure, unpaid balances, and an upgrade affect return of the deposit."], ["Choose a payment routine before rewards", "Set a manageable spending limit and arrange payments you can afford. On-time payments and careful balance management matter more than a small reward rate. If you want to check eligibility first, read whether the issuer uses a soft or hard credit inquiry."]], "links": [["/learn/building-credit/secured-vs-unsecured-cards", "Secured versus unsecured cards"], ["/credit-cards/no-fee", "Compare no-annual-fee options"], ["/calculators/debt-payoff", "Plan your repayments"]]};
export const metadata={title:guide.title,description:guide.intro,alternates:{canonical:"/credit-cards/secured"}};
export default function Page(){const cards=cardsByCategory("secured");return <>
<BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name:guide.title,href:'/credit-cards/secured'}]}/>
<header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-10"><span className="chip chip-lime mb-5">Credit card comparison</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight max-w-4xl">{guide.title}</h1><p className="text-lg text-mute mt-6 max-w-3xl">{guide.intro}</p><a href="#compare" className="pill pill-ink mt-6">Compare listed cards ↓</a></header>
<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">What to compare before applying</h2><div className="grid md:grid-cols-3 gap-5">{guide.sections.map(([title,text])=><article key={title} className="card p-6"><h3 className="font-bold text-xl mb-3">{title}</h3><p className="text-mute leading-relaxed">{text}</p></article>)}</div></section>
<section id="compare" className="max-w-(--max-w-page) mx-auto px-6 py-10"><h2 className="font-display text-3xl font-bold mb-4">Compare the cards in our directory</h2><p className="text-mute mb-8 max-w-3xl">This is a selection of products, not the entire market. Offers can vary by applicant and change over time. Verify current bonuses, rates, fees, and eligibility in the issuer’s application disclosures before applying. List order is not a guarantee of suitability or approval.</p><div className="space-y-5">{cards.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>
<section className="max-w-(--max-w-page) mx-auto px-6 py-12"><h2 className="font-display text-2xl font-bold mb-4">Continue your comparison</h2><div className="flex flex-wrap gap-4">{guide.links.map(([href,label])=><Link className="pill pill-ghost" key={href} href={href!}>{label}</Link>)}</div><p className="text-sm text-mute mt-8">Comparison guidance reviewed September 12, 2026. This date does not certify every issuer offer as current. Sources: <a className="underline" href="https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/">CFPB credit card terms</a> and each linked issuer’s application disclosures. <Link className="underline" href="/editorial-policy">Editorial policy</Link>.</p></section><CardDecisionGuides comparisonHref="/credit-cards/secured" /></>}
