import { CardDecisionGuides } from "@/components/card-decision-guides";
import Link from "next/link";
import {cardsByCategory} from "@/lib/cards-server";
import {CardPickRow} from "@/components/card-pick-row";
import {BreadcrumbListSchema} from "@/components/schemas";
const guide={"category": "no-annual-fee", "title": "No Annual Fee Credit Cards: Compare Rewards & Bonuses", "intro": "Compare no-annual-fee credit cards by ongoing rewards, welcome-bonus requirements, and borrowing costs. A $0 annual fee does not remove interest or other charges.", "sections": [["How to compare a no-annual-fee signup bonus", "Start with spending you already plan to make. Check the qualifying purchase amount, deadline, exclusions, and any previous-cardholder restrictions in the issuer offer. A larger bonus is less useful if it requires spending beyond your budget."], ["Compare year two as well as year one", "Separate a one-time bonus from ongoing rewards. For illustration, 2% cash back on $12,000 of eligible purchases is $240; 1.5% is $180. These are calculation assumptions, not quotes for a specific card. Category caps and redemption rules can change the result."], ["No annual fee does not mean free borrowing", "Compare purchase APR, balance-transfer fees, foreign-transaction fees, and the rate after any introductory offer. If you expect to carry a balance, interest costs deserve more attention than rewards."]], "links": [["/credit-cards/zero-apr", "Compare introductory APR options"], ["/credit-cards/secured", "Compare secured cards"], ["/calculators/debt-payoff", "Calculate a balance payoff"]]};
export const metadata={title:guide.title,description:guide.intro,alternates:{canonical:"/credit-cards/no-fee"}};
export default function Page(){const cards=cardsByCategory("no-annual-fee");return <>
<BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name:guide.title,href:'/credit-cards/no-fee'}]}/>
<header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-10"><span className="chip chip-lime mb-5">Credit card comparison</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight max-w-4xl">{guide.title}</h1><p className="text-lg text-mute mt-6 max-w-3xl">{guide.intro}</p><a href="#compare" className="pill pill-ink mt-6">Compare listed cards ↓</a></header>
<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">What to compare before applying</h2><div className="grid md:grid-cols-3 gap-5">{guide.sections.map(([title,text])=><article key={title} className="card p-6"><h3 className="font-bold text-xl mb-3">{title}</h3><p className="text-mute leading-relaxed">{text}</p></article>)}</div></section>
<section id="compare" className="max-w-(--max-w-page) mx-auto px-6 py-10"><h2 className="font-display text-3xl font-bold mb-4">Compare the cards in our directory</h2><p className="text-mute mb-8 max-w-3xl">This is a selection of products, not the entire market. Offers can vary by applicant and change over time. Verify current bonuses, rates, fees, and eligibility in the issuer’s application disclosures before applying. List order is not a guarantee of suitability or approval.</p><div className="space-y-5">{cards.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>
<section className="max-w-(--max-w-page) mx-auto px-6 py-12"><h2 className="font-display text-2xl font-bold mb-4">Continue your comparison</h2><div className="flex flex-wrap gap-4">{guide.links.map(([href,label])=><Link className="pill pill-ghost" key={href} href={href!}>{label}</Link>)}</div><p className="text-sm text-mute mt-8">Comparison guidance reviewed September 12, 2026. This date does not certify every issuer offer as current. Sources: <a className="underline" href="https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/">CFPB credit card terms</a> and each linked issuer’s application disclosures. <Link className="underline" href="/editorial-policy">Editorial policy</Link>.</p></section><CardDecisionGuides comparisonHref="/credit-cards/no-fee" /></>}
