import Link from 'next/link';
import { EditorialNote } from './editorial-note';
import { BreadcrumbListSchema, FAQPageSchema } from './schemas';
const coverage='https://www.libertymutual.com/vehicle/auto-insurance/coverage';
const discounts='https://www.libertymutual.com/vehicle/auto-insurance/discounts';
const terms='https://www.libertymutual.com/marketing-disclaimer';
const faqs=[
 {question:'How much does Liberty Mutual car insurance cost?',answer:'A personalized quote is needed. We do not have a documented rate sample that supports a national average for this review. Compare quotes using the same drivers, vehicles, limits, deductibles, and policy period.'},
 {question:'Does Liberty Mutual offer bundling discounts?',answer:'Liberty Mutual lists a multi-policy discount. Eligibility and savings vary. Compare the total combined premium with separate policies instead of assuming a fixed percentage applies to both.'},
 {question:'Does RightTrack guarantee a lower renewal price?',answer:'No universal price guarantee should be assumed. Check the program terms for your state, the driving data collected, and how participation affects the quoted and renewal premiums.'},
 {question:'Is every coverage option available in every state?',answer:'No. Liberty Mutual states that coverages and discounts vary by state and eligibility. The policy documents and quote determine what is available to you.'},
];
export function LibertyAutoReview(){return <article className="max-w-(--max-w-page) mx-auto px-6 py-12">
 <BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Auto insurance',href:'/insurance/auto'},{name:'Liberty Mutual',href:'/insurance/auto/liberty-mutual-auto'}]}/><FAQPageSchema items={faqs}/>
 <span className="chip chip-lime mb-5">Auto insurance review</span><h1 className="font-display font-bold text-4xl md:text-5xl tracking-tight max-w-4xl">Liberty Mutual auto insurance: coverage, discounts and trade-offs</h1>
 <p className="text-lg text-mute mt-5 max-w-3xl">A useful quote to compare if you want optional vehicle protection or may qualify for several discounts. Whether it offers good value depends on your actual premium and policy terms.</p><EditorialNote checked="2026-09-11"/>
 <div className="grid sm:grid-cols-3 gap-4 my-8">{[['Price','Personalized quote'],['Discounts','Eligibility varies'],['Fintiex score','No score assigned']].map(([a,b])=><div key={a} className="card p-6"><p className="text-sm text-mute">{a}</p><strong className="block text-xl mt-2">{b}</strong></div>)}</div>
 <a href="https://www.libertymutual.com/vehicle/auto-insurance" className="pill pill-ink" target="_blank" rel="nofollow noreferrer">Check Liberty Mutual coverage and quote ↗</a>
 <section className="max-w-3xl space-y-5 my-12"><h2 className="font-display text-3xl font-bold">Coverage to compare</h2><p>Liberty Mutual lists liability, collision, comprehensive, uninsured-motorist, medical-payments, and personal-injury protection options. It also describes optional rental reimbursement, roadside assistance, gap coverage, and vehicle replacement products. Availability depends on your state and eligibility. <a className="underline" href={coverage}>Provider coverage guide</a>.</p><p>Start with the protection you need, then compare prices for that same package. Ask whether a replacement option has vehicle-age, mileage, ownership, or total-loss conditions. A lower deductible can change the premium; compare both together.</p>
 <h2 className="font-display text-3xl font-bold">Discounts and RightTrack</h2><p>The provider lists multi-policy, multi-car, paperless, payment, student, military, claims-free, and driving-related discounts, among others. Its RightTrack program uses driving information. Do not add advertised discount percentages together or assume that every discount applies to the entire premium. <a className="underline" href={discounts}>Current discount descriptions</a> and <a className="underline" href={terms}>eligibility and marketing terms</a>.</p><p>Ask for a quote with and without optional driving monitoring, where available. Review which data is collected, how long monitoring lasts, and whether the result can affect later pricing in your state. Compare bundled auto and home costs against the cost of buying the policies separately.</p>
 <h2 className="font-display text-3xl font-bold">When to include it in your shortlist</h2><p>Consider requesting a quote when a specific optional coverage matters to you or when your household may qualify for multiple discounts. Compare at least two other offers using identical coverage and a matching policy period. A percentage saving is less useful than the final price for equivalent protection.</p><h2 className="font-display text-3xl font-bold">What this review cannot establish</h2><p>We have not run a representative quote study, tested a claim, or verified a current regional customer-satisfaction score. The previous numerical rating and premium range did not include enough supporting evidence and have been removed. This page does not rank Liberty Mutual above other insurers.</p>
 <h2 className="font-display text-3xl font-bold">Before accepting a quote</h2><ol className="list-decimal pl-5 space-y-3"><li>Match liability limits, deductibles, drivers, vehicles, and optional coverages.</li><li>Compare the total policy cost, installment fees, and renewal assumptions.</li><li>Read exclusions and confirm the underwriting company named on the policy.</li><li>Check how to report a claim and what evidence you would need.</li></ol></section>
 <section className="max-w-3xl my-12"><h2 className="font-display text-3xl font-bold">Common questions</h2>{faqs.map(f=><div key={f.question} className="mt-6"><h3 className="font-semibold text-xl">{f.question}</h3><p className="mt-2 text-mute">{f.answer}</p></div>)}</section>
 <p className="border-t border-line pt-6 text-sm text-mute">Provider pages checked September 11, 2026. Sources: <a className="underline" href={coverage}>coverage</a>, <a className="underline" href={discounts}>discounts</a>, and <a className="underline" href={terms}>disclosures</a>. <Link className="underline" href="/editorial-policy">Read our methodology</Link>.</p><p className="mt-5"><Link className="underline" href="/insurance/auto">Compare auto insurers</Link> · <Link className="underline" href="/insurance/auto/geico-auto">GEICO overview</Link> · <Link className="underline" href="/insurance/auto/progressive-auto">Progressive overview</Link></p>
 </article>}
