import Link from "next/link";
import { savingsOffer, rateLabel } from "@/lib/savings-rates";
export function SavingsReviewDecision({ offerKey }: { offerKey: string }) {
  if (offerKey !== "marcus" && offerKey !== "ally") return null;
  const marcus = savingsOffer("marcus"), ally = savingsOffer("ally");
  return <section className="my-12 max-w-4xl"><h2 className="font-display text-3xl font-bold mb-5">Marcus vs. Ally: rate, access and savings goals</h2><p className="text-mute mb-5">Use the standard rate for an ongoing comparison. A limited referral boost can change the first few months without changing which account fits your day-to-day needs.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm min-w-[520px]"><caption className="sr-only">Marcus and Ally savings comparison</caption><thead><tr><th className="p-3" scope="col">Consideration</th><th className="p-3" scope="col">Marcus</th><th className="p-3" scope="col">Ally</th></tr></thead><tbody><tr className="border-t border-line"><th className="p-3" scope="row">Observed standard APY</th><td className="p-3">{rateLabel(marcus.apy)} · {marcus.checked}</td><td className="p-3">{rateLabel(ally.apy)} · {ally.checked}</td></tr><tr className="border-t border-line"><th className="p-3" scope="row">Monthly maintenance fee / opening minimum</th><td className="p-3">$0 / $0</td><td className="p-3">$0 / $0</td></tr><tr className="border-t border-line"><th className="p-3" scope="row">What to investigate</th><td className="p-3">External-account transfer timing and holds</td><td className="p-3">Savings buckets, transfer limits and access</td></tr></tbody></table></div>
    <h3 className="text-xl font-bold mt-8 mb-3">Translate a rate gap into dollars</h3><p className="text-mute">A 0.50 percentage-point APY difference is about $50 over one year on an unchanged $10,000 balance, or $250 on $50,000, if both rates stay unchanged. Compare that amount with the value of convenient access and any fees. These examples assume no deposits or withdrawals and are before tax; they are not a forecast.</p>
    <h3 className="text-xl font-bold mt-8 mb-3">Before moving an emergency fund</h3><p className="text-mute">Keep near-term bill money available while testing your transfer route. Ally limits certain withdrawals and transfers to 10 per statement cycle; it says repeated excess activity can lead to account closure even though there is no excess-transaction fee. Marcus processes eligible transfers of $100,000 or less requested by noon Eastern on a business day by 5 p.m.; the receiving bank and holds can still affect access.</p><p className="mt-4 text-sm text-mute">Features checked September 23, 2026: <a className="u-link" href="https://www.marcus.com/us/en/savings/high-yield-savings">Marcus account terms</a> · <a className="u-link" href="https://www.ally.com/bank/online-savings-account/">Ally account terms</a>. Rate check dates appear separately above.</p><div className="flex flex-wrap gap-4 mt-6"><Link className="u-link" href={offerKey === "marcus" ? "/reviews/ally" : "/reviews/marcus"}>Read the other account review</Link><Link className="u-link" href="/calculators/savings-goal">Calculate your savings timeline</Link></div></section>;
}
