import Link from "next/link";
import {cardsByCategory} from "@/lib/cards-server";
import {CardPickRow} from "@/components/card-pick-row";
import {BreadcrumbListSchema} from "@/components/schemas";
const guide={"category": "travel", "title": "Travel Credit Cards: Compare Annual Fees & Rewards", "intro": "Compare travel credit cards by annual cost, redemption options, and benefits you will actually use. A large points offer is not the same as a guaranteed cash value.", "sections": [["Cash-like rewards or transfer partners?", "Check how points can be redeemed, whether travel must be booked through a particular portal, and the rules for transfers. Compare the cash price of the same trip with the points, taxes, and fees required. Do not assume that every point has one fixed value."], ["Value benefits at your own usage", "Subtract the annual fee from rewards and credits you realistically expect to use. A credit restricted to a merchant, booking channel, or month may be worth less to you than its face value. Check enrollment, guest-access, and booking conditions before counting a benefit."], ["Check costs when traveling abroad", "Read the foreign-transaction fee and payment-network acceptance information. Review the guide to benefits for insurance eligibility and exclusions. If you carry a balance, borrowing costs can outweigh the value of travel rewards."]], "links": [["/credit-cards/no-fee", "Compare no-annual-fee cards"], ["/credit-cards/business", "Travel cards for business expenses"], ["/credit-cards/cash-back", "Compare cash-back alternatives"]]};
export const metadata={title:guide.title,description:guide.intro,alternates:{canonical:"/credit-cards/travel"}};
export default function Page(){const cards=cardsByCategory("travel");return <>
<BreadcrumbListSchema items={[{name:'Home',href:'/'},{name:'Credit cards',href:'/credit-cards'},{name:guide.title,href:'/credit-cards/travel'}]}/>
<header className="max-w-(--max-w-page) mx-auto px-6 pt-16 pb-10"><span className="chip chip-lime mb-5">Credit card comparison</span><h1 className="font-display font-extrabold text-4xl md:text-5xl tracking-tight max-w-4xl">{guide.title}</h1><p className="text-lg text-mute mt-6 max-w-3xl">{guide.intro}</p><a href="#compare" className="pill pill-ink mt-6">Compare listed cards ↓</a></header>
<section className="max-w-(--max-w-page) mx-auto px-6 pb-12"><h2 className="font-display text-3xl font-bold mb-6">What to compare before applying</h2><div className="grid md:grid-cols-3 gap-5">{guide.sections.map(([title,text])=><article key={title} className="card p-6"><h3 className="font-bold text-xl mb-3">{title}</h3><p className="text-mute leading-relaxed">{text}</p></article>)}</div></section>
<section id="compare" className="max-w-(--max-w-page) mx-auto px-6 py-10"><h2 className="font-display text-3xl font-bold mb-4">Compare the cards in our directory</h2><p className="text-mute mb-8 max-w-3xl">This is a selection of products, not the entire market. Offers can vary by applicant and change over time. Verify current bonuses, rates, fees, and eligibility in the issuer’s application disclosures before applying. List order is not a guarantee of suitability or approval.</p><div className="space-y-5">{cards.map(c=><CardPickRow key={c.slug} card={c}/>)}</div></section>
<section className="max-w-(--max-w-page) mx-auto px-6 py-12"><h2 className="font-display text-2xl font-bold mb-4">Continue your comparison</h2><div className="flex flex-wrap gap-4">{guide.links.map(([href,label])=><Link className="pill pill-ghost" key={href} href={href!}>{label}</Link>)}</div><p className="text-sm text-mute mt-8">Comparison guidance reviewed September 12, 2026. This date does not certify every issuer offer as current. Sources: <a className="underline" href="https://www.consumerfinance.gov/consumer-tools/credit-cards/answers/key-terms/">CFPB credit card terms</a> and each linked issuer’s application disclosures. <Link className="underline" href="/editorial-policy">Editorial policy</Link>.</p></section></>}
